version: '3.8'

services:
  lighthouse-service:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - MONGODB_URI=${MONGODB_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROME_PATH=${CHROME_PATH}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:${MONGO_VERSION:-latest}
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE:-lighthouse}
    volumes:
      - ${MONGO_DATA_VOLUME:-mongodb_data}:/data/db
    restart: unless-stopped

volumes:
  ${MONGO_DATA_VOLUME:-mongodb_data}: 